name: "coscmd"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: coscmd
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: jdnoob/coscmd
          dockerFile: coscmd/Dockerfile
          platform: linux/amd64,linux/arm64
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
