name: "JD_test_v4"
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Aliyun Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      -
        name: Build V4_test_BOT and push
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          pull: false
          push: true
          context: jd
          file: jd/test_v4-bot.Dockerfile
          platforms: linux/arm64/v8
          tags: ${{ secrets.ALIYUN_REGISTRY }}${{ secrets.ALIYUN_URL }}:test_bot
          build-args: |
            JD_SHELL_KEY=${{ secrets.JD_SHELL_KEY }}
            JD_SCRIPTS_KEY=${{ secrets.JD_SCRIPTS_KEY }}