name: "JD_v3"
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build tools and push
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          context: jd
          file: jd/v3-test.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: noobx/jd:v3-test
          build-args: |
            JD_TOOLS_KEY=${{ secrets.JD_TOOLS_KEY }}
            JD_SCRIPTS_KEY=${{ secrets.JD_SCRIPTS_KEY }}
      -
        name: Build V3-BOT and push
        id: docker_build_2
        uses: docker/build-push-action@v2
        with:
          pull: false
          push: true
          context: jd
          file: jd/v3-bot-test.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: noobx/jd:v3-bot-test