name: "JD_v2"
on:
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build V2 and push
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          context: jd
          file: jd/v2.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          tags: noobx/jd:gitee
          build-args: |
            JD_SCRIPTS_KEY=${{ secrets.JD_SCRIPTS_KEY }}